# Generated by Django 3.1.5 on 2021-01-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210122_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='order_id',
            new_name='reg_id',
        ),
    ]
