# Generated by Django 3.1.5 on 2021-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210123_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='takeaway',
            field=models.TimeField(null=True),
        ),
    ]
